---
name: publish-maven-artifact

on:
  workflow_call:
    inputs:
      release_scope:
        description: Git tagging release scope, such as major, minor, or patch.
        default: minor
        type: string
        required: true
    secrets:
      google_cloud_service_account_key:
        description: Optional Google Cloud service account key, assuming setup_google_cloud_auth is true.
        required: true
      caller_github_token:
        description: Standard github.token used for git-tagging the release version against the calling repository.
        required: true
      ast_publish_username:
        description: Username for accessing the ast repository.
        required: false
      ast_publish_password:
        description: Password for accessing the ast repository.
        required: false
      moderne_artifactory_username:
        description: Username for accessing the https://artifactory.moderne.ninja/artifactory/moderne-private repository.
        required: true
      moderne_artifactory_password:
        description: Password for accessing the https://artifactory.moderne.ninja/artifactory/moderne-private repository.
        required: true

env:
  GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
  GRADLE_SWITCHES: "--console=plain --info --stacktrace --no-daemon"
  GRGIT_AUTH_SWITCHES: "-Dorg.ajoberstar.grgit.auth.username=${{github.actor}} -Dorg.ajoberstar.grgit.auth.password=${{secrets.caller_github_token}}"
  AST_PUBLISH_USERNAME: ${{ secrets.ast_publish_username }}
  AST_PUBLISH_PASSWORD: ${{ secrets.ast_publish_password }}
  MODERNE_ARTIFACTORY_USERNAME: ${{ secrets.moderne_artifactory_username }}
  MODERNE_ARTIFACTORY_PASSWORD: ${{ secrets.moderne_artifactory_password }}

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'moderneinc'
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set-up-jdk
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: "gradle"
      - name: configure-git-user
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: setup-gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.google_cloud_service_account_key }}
      - uses: google-github-actions/setup-gcloud@v1.1.1
      - name: build, test, and publish jar
        run: ./gradlew ${GRADLE_SWITCHES} ${GRGIT_AUTH_SWITCHES} -Prelease.scope=${{ inputs.release_scope }} final
